Erweiterung um relevante Daten Tilgungssatz-Wechsel
hypoport/europace-productengine-api pull request #36
Opened 2021-07-19 14:22 UTC by axiOli

[ITDEV-140]

Um Aufschläge rund um Tilgungssatzwechsel in Finmas PE umzusetzen (analog Speed: **PPK-1343**) müssen Anfrage + Antwort erweitert werden

[ITDEV-140]: https://finmas.atlassian.net/browse/ITDEV-140

2021-07-28 11:16 UTC, jaxilaris commented
@twessendorf @dlonshakov  - könntet ihr bitte die Änderungen reviewen?

2021-07-29 08:36 UTC, twessendorf approved these changes
LGTM

2021-07-29 08:37 UTC, twessendorf requested changes

2021-07-29 08:37 UTC, twessendorf commented on api.json
> +        "praeferierteAnzahlTilgungsSatzWechsel": {
Hier bitte Tilgungssatz genauso camelcasen wie oben

2021-07-29 08:44 UTC, twessendorf commented on api.json
> +        "praeferierteAnzahlTilgungsSatzWechsel": {
Ich habe nochmal nachgeschaut. Leider ist Tilgungssatz bisher in der API nicht konsistent umgesetzt, mal mit Binnenmajuskel (`TilgungsSatz`), mal ohne.
Bei Europace hatten wir uns mal darauf verständigt, als externe Wahrheit https://www.dwds.de/ zu nutzen: Steht das Wort dort in einem Wörterbuch, kann man es ohne Binnenmajuskel schreiben, sonst mit. Bei Tilgungssatz ist das nicht der Fall, daher würde ich hier für `TilgungsSatz` plädieren

2021-07-29 08:46 UTC, twessendorf commented on api.json
> +        "praeferierteAnzahlTilgungsSatzWechsel": {
Dazu gab es im Europace-Slack noch einen Hinweise:
"Obacht: DWDS zeigt immer eine Zerlegung an. Oberhalb des “Wörterbucheintrags” erscheint ein Hinweis, ob das Wort ein echter Wörterbucheintrag ist, oder ob er automatisch generiert wurde. Vergleiche https://www.dwds.de/wb/F%C3%B6rderbank und https://www.dwds.de/?q=Vorgangsnummer&from=wb Daraus folgt: wir schreiben `Foerderbank` aber `VorgangsNummer`"

2021-07-29 08:46 UTC, twessendorf commented on api.json
> +        "praeferierteAnzahlTilgungsSatzWechsel": {
Wollen wir das hier auch so handhaben?

2021-07-29 09:53 UTC, twessendorf approved these changes

2021-07-29 09:53 UTC, merged