Erweiterung Vorlasten
hypoport/europace-productengine-api pull request #37
Opened 2021-07-20 08:28 UTC by axiOli

[ITDEV-156]

Analog Speed (**PPK-1681**) sollen in der Finmas PE die Vorlasten mit Restschuld bewertet werden können.

Dazu muss die Restschuld übertragen werden.

Im Rahmen von **PPK-1344** wurde außerdem das Feld `wert` in `grundschuld` umbenannt. Um späterer Verwirrung vorzubeugen, empfiehlt es sich wahrscheinlich, das auch in PAPI umzubenennen. Wie wollen wir mit sowas umgehen? (deprecated Felder usw.)

[ITDEV-156]: https://finmas.atlassian.net/browse/ITDEV-156

2021-07-28 08:37 UTC, jaxilaris commented
@dlonshakov @twessendorf  - Könntet ihr bitte den Pull Request reviewen?

2021-07-29 08:33 UTC, twessendorf commented
@jaxilaris Wenn `grundschuld` das Feld `wert` ablöst, sollten wir es mit `deprecated` und einer entsprechenden `description` versehen (siehe hierzu vergleichend auch das Feld `gewerbeFlaecheNettoKaltmieteProQmMonatlich` aus der API)

2021-07-29 08:34 UTC, twessendorf requested changes

2021-07-29 08:34 UTC, twessendorf commented on api.json
> +        "grundschuld": {
Wenn `grundschuld` das Feld `wert` ablöst, sollten wir es mit `deprecated` und einer entsprechenden `description` versehen (siehe hierzu vergleichend auch das Feld `gewerbeFlaecheNettoKaltmieteProQmMonatlich` aus der API)

2021-07-29 09:08 UTC, twessendorf approved these changes
LGTM

2021-07-29 09:14 UTC, merged