[MTV] Erweiterung der API um Bearbeitungszeiten
hypoport/europace-productengine-api pull request #60
Opened 2023-10-24 10:40 UTC by fgellhorn

Erweiterung der Antwort um Bearbeitungszeiten, damit auch die Finmas Produkte diese liefern können.

2023-10-24 14:37 UTC, HypoStephan commented on api.json
> +        "anmerkung":{
Zwischen `"anmerkung":` und `{` fehlt noch ein Leerzeichen

2023-10-24 14:42 UTC, fgellhorn commented on api.json
> +        "bearbeitungszeitVom": {
Das ist das Datum aus dem Customizing zu welchem die Bearbeitungszeit letztmalig angepasst wurde.

2023-10-24 15:08 UTC, HypoStephan commented on api.json
> +        "bearbeitungszeitVom": {
Vorschlag für Benennung: 
`standBearbeitungszeit` _oder_ 
`bearbeitungszeitEintragDatum` _oder_ 
`bearbeitungszeitEintragVom` _oder_ 
`letzteAnpassungBearbeitungszeit`

2023-10-25 05:54 UTC, fgellhorn commented on api.json
> +        "bearbeitungszeitVom": {
Dann hätten wir hier eine Abweichung zu den anderen Services. Im Sinne einer einheitlichen Bezeichnung würde ich das gern so lassen.

2023-10-25 07:43 UTC, HypoStephan commented on api.json
> +        "bearbeitungszeitVom": {
Tut mir leid, ich finde die Bezeichnung nicht eindeutig genug, unabhängig davon wie die anderen Services diesen Wert benennen. Bitte verwende hier noch einen aussagekräftigeren Namen.

2023-10-25 07:43 UTC, HypoStephan requested changes
Siehe mein letzter Kommentar

2023-10-25 11:22 UTC, HypoStephan approved these changes
LGTM :) Danke für die Anpassung!

2023-10-25 11:22 UTC, merged